notifications:
  email:
    - dean@airdb.com
dist: trusty
sudo: required

language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
env:
  WechatMSG="https://aws.airdb.io/wechat/sendmsg"
  TARVIS_URL="https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
  RELEASE_URL="https://www.airdb.com/website/dist_${TRAVIS_COMMIT}/index.html"

# cache components
before_install:
    - which npm
    - npm install -g vuepress
install:
    - ls -l
before_script:
    - echo "before_script"
script:
    - npm install
    - npm run build
after_success:
    - cp favicon.ico ./.vuepress/dist
    - cd ./.vuepress/dist
    - echo 'www.airdb.com' > CNAME
    - git init
    - git config user.name "${U_NAME}"
    - git config user.email "${U_EMAIL}"
    - git add -A
    - git commit -m "Auto Update by Travis-CI"
    - echo git push --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
    - git push --force "https://${GH_TOKEN}@${GH_REF}" master
