name: Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g vuepress
        npm install
        npm run build --if-present
        cd ./.vuepress/dist
        echo 'www.airdb.com' > CNAME
        git init
        git config user.name "airdb-bot"
        git config user.email "airdb-bot@airdb.com"
        git add -A
        git commit -m "Auto Update by actions"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}" master:gh-pages
      env:
        CI: true
